# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "pyyaml>=6.0",
# ]
# ///
"""导出当前激活的 Clash Verge 配置为 Android 可直接导入的 YAML。

默认读取 Clash Verge Rev 当前生效的 clash-verge.yaml，并保留住宅链式代理的
`dialer-proxy` 为主代理组名，方便在手机端自行切换第一跳上游节点。
"""

from __future__ import annotations

import argparse
import copy
import sys
from pathlib import Path

import yaml


DEFAULT_VERGE_DIR = Path.home() / "Library/Application Support/io.github.clash-verge-rev.clash-verge-rev"
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_COMPONENT_PATH = PROJECT_ROOT / "injection_component.yaml"
DEFAULT_OUTPUT_PATH = PROJECT_ROOT / "clash-meta-android.yaml"
DEFAULT_PACKAGE_NAME = "com.anthropic.claude"
DIALER_PROXY_PLACEHOLDER = "__DIALER_PROXY__"
DEFAULT_DNS_SERVERS = ["223.5.5.5", "119.29.29.29"]


def load_yaml(path: Path) -> dict:
    with open(path, encoding="utf-8") as handle:
        return yaml.safe_load(handle) or {}


def dump_yaml(path: Path, data: dict) -> None:
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("# Auto-generated by export_android.py\n")
        handle.write("# Copy this file to Clash Meta for Android and import it directly.\n\n")
        yaml.safe_dump(data, handle, allow_unicode=True, sort_keys=False)


def require_file(path: Path, label: str) -> None:
    if not path.is_file():
        print(f"错误: {label} 不存在: {path}", file=sys.stderr)
        sys.exit(1)


def get_current_profile_item(profiles_yaml: dict) -> dict:
    current_uid = profiles_yaml.get("current")
    if not current_uid:
        print("错误: profiles.yaml 中没有 current", file=sys.stderr)
        sys.exit(1)

    for item in profiles_yaml.get("items", []):
        if item.get("uid") == current_uid:
            return item

    print(f"错误: 当前激活 profile 未找到: {current_uid}", file=sys.stderr)
    sys.exit(1)


def detect_main_group(active_profile_yaml: dict) -> str | None:
    groups = active_profile_yaml.get("proxy-groups") or []
    if groups and isinstance(groups[0], dict):
        return groups[0].get("name")
    return None


def replace_dialer_proxy(proxies: list[dict], dialer_proxy: str) -> list[dict]:
    result = copy.deepcopy(proxies)
    for proxy in result:
        if proxy.get("dialer-proxy") == DIALER_PROXY_PLACEHOLDER:
            proxy["dialer-proxy"] = dialer_proxy
        if proxy.get("type") == "socks5":
            proxy["udp"] = True
    return result


def upsert_named_items(items: list[dict], additions: list[dict]) -> list[dict]:
    result = list(items)
    index_by_name = {
        item.get("name"): idx
        for idx, item in enumerate(result)
        if isinstance(item, dict) and item.get("name")
    }

    for addition in additions:
        name = addition.get("name")
        if name and name in index_by_name:
            result[index_by_name[name]] = addition
            continue
        result.append(addition)

    return result


def build_mobile_rules(package_name: str, chain_group_name: str, domain_rules: list[str]) -> list[str]:
    return [
        f"AND,((PROCESS-NAME-WILDCARD,{package_name}*),(NETWORK,udp)),{chain_group_name}",
        f"AND,((PROCESS-NAME-WILDCARD,{package_name}*),(NETWORK,tcp)),{chain_group_name}",
        *domain_rules,
    ]


def filter_rules(existing_rules: list[str], managed_rules: list[str]) -> list[str]:
    managed_set = set(managed_rules)
    result: list[str] = []

    for rule in existing_rules:
        if rule in managed_set:
            continue
        if rule.startswith("PROCESS-NAME,SunBrowser,"):
            continue
        if rule.startswith("PROCESS-NAME,SunBrowser Helper,"):
            continue
        if rule.startswith("PROCESS-NAME,AdsPower Global Helper,"):
            continue
        if rule.startswith("PROCESS-NAME,AdsPower Global,"):
            continue
        result.append(rule)

    return result


def sanitize_dns_servers(servers: object) -> list[str]:
    if not isinstance(servers, list):
        return []
    return [entry for entry in servers if isinstance(entry, str) and "#h3" not in entry.lower()]


def sanitize_for_android(config: dict) -> dict:
    cleaned = copy.deepcopy(config)

    cleaned.pop("external-controller-unix", None)
    cleaned.pop("external-controller-cors", None)
    if cleaned.get("external-controller") == "":
        cleaned.pop("external-controller", None)
    if cleaned.get("secret") == "set-your-secret":
        cleaned.pop("secret", None)

    tun = cleaned.get("tun")
    if isinstance(tun, dict):
        tun.pop("device", None)
        tun.setdefault("enable", True)
        tun.setdefault("stack", "gvisor")
        tun.setdefault("dns-hijack", ["any:53"])

    profile = cleaned.setdefault("profile", {})
    profile.setdefault("store-selected", True)

    dns = cleaned.setdefault("dns", {})
    dns["enable"] = True
    dns["enhanced-mode"] = "fake-ip"
    dns["prefer-h3"] = False
    dns["ipv6"] = False
    dns["respect-rules"] = True

    nameserver = sanitize_dns_servers(dns.get("nameserver"))
    proxy_server_nameserver = sanitize_dns_servers(dns.get("proxy-server-nameserver"))
    fallback = sanitize_dns_servers(dns.get("fallback"))

    if not nameserver:
        nameserver = list(DEFAULT_DNS_SERVERS)
    if not proxy_server_nameserver:
        proxy_server_nameserver = list(nameserver or fallback or DEFAULT_DNS_SERVERS)

    dns["nameserver"] = nameserver
    dns["proxy-server-nameserver"] = proxy_server_nameserver

    cleaned["find-process-mode"] = "always"
    cleaned["ipv6"] = False
    cleaned.setdefault("clash-for-android", {})
    cleaned["clash-for-android"]["append-system-dns"] = False

    return cleaned


def main() -> None:
    parser = argparse.ArgumentParser(description="导出当前激活配置为 Clash Meta for Android 可导入 YAML")
    parser.add_argument(
        "--verge-dir",
        type=Path,
        default=DEFAULT_VERGE_DIR,
        help=f"Clash Verge Rev 配置目录 (默认: {DEFAULT_VERGE_DIR})",
    )
    parser.add_argument(
        "--component",
        type=Path,
        default=DEFAULT_COMPONENT_PATH,
        help="链式代理组件定义文件路径",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help=f"导出文件路径 (默认: {DEFAULT_OUTPUT_PATH})",
    )
    parser.add_argument(
        "--package-name",
        default=DEFAULT_PACKAGE_NAME,
        help=f"Claude Android 包名 (默认: {DEFAULT_PACKAGE_NAME})",
    )
    parser.add_argument("--dry-run", action="store_true", help="只打印导出摘要，不写文件")
    args = parser.parse_args()

    verge_dir = args.verge_dir.expanduser()
    active_config_path = verge_dir / "clash-verge.yaml"
    profiles_path = verge_dir / "profiles.yaml"
    active_profile_path: Path | None = None

    require_file(active_config_path, "当前生效配置 clash-verge.yaml")
    require_file(profiles_path, "profiles.yaml")
    require_file(args.component, "injection_component.yaml")

    active_config = load_yaml(active_config_path)
    profiles_yaml = load_yaml(profiles_path)
    current_item = get_current_profile_item(profiles_yaml)

    profiles_dir = verge_dir / "profiles"
    if current_item.get("uid"):
        candidate = profiles_dir / f"{current_item['uid']}.yaml"
        if candidate.is_file():
            active_profile_path = candidate

    if active_profile_path is None:
        print("错误: 当前激活订阅 YAML 未找到，无法冻结上游节点", file=sys.stderr)
        sys.exit(1)

    active_profile_yaml = load_yaml(active_profile_path)
    main_group = detect_main_group(active_profile_yaml)
    if not main_group:
        print("错误: 无法识别当前激活链路的主代理组", file=sys.stderr)
        sys.exit(1)

    component = load_yaml(args.component)
    component_proxies = replace_dialer_proxy(component.get("proxies") or [], main_group)
    component_groups = copy.deepcopy(component.get("proxy-groups") or [])
    chain_group_name = component_groups[0]["name"] if component_groups else "Claude-住宅链式专线"

    domain_rules = [rule for rule in component.get("rules") or [] if not rule.startswith("PROCESS-NAME,")]
    managed_rules = build_mobile_rules(args.package_name, chain_group_name, domain_rules)

    android_config = sanitize_for_android(active_config)
    android_config["proxies"] = upsert_named_items(android_config.get("proxies") or [], component_proxies)
    android_config["proxy-groups"] = upsert_named_items(android_config.get("proxy-groups") or [], component_groups)

    existing_rules = android_config.get("rules") or []
    android_config["rules"] = [*managed_rules, *filter_rules(existing_rules, managed_rules)]

    summary = [
        f"当前激活订阅: {current_item.get('name') or current_item.get('uid')}",
        f"dialer-proxy 主代理组: {main_group}",
        f"链式代理组: {chain_group_name}",
        f"Claude Android 包名: {args.package_name}",
        "Android UDP: 默认走住宅链式代理",
        f"输出文件: {args.output.expanduser()}",
    ]

    print("\n".join(summary))
    if args.dry_run:
        return

    output_path = args.output.expanduser()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    dump_yaml(output_path, android_config)
    print("导出完成，可直接复制到手机导入 Clash Meta for Android。")


if __name__ == "__main__":
    main()
