# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "pyyaml>=6.0",
# ]
# ///
"""Clash Verge Rev 住宅IP链式代理注入工具

将 injection_component.yaml 中定义的代理节点、代理组和规则
写入 Clash Verge Rev 的 Script 配置文件，订阅更新后不会丢失。

支持多订阅: 自动遍历所有 remote 订阅，检测各自的主代理组名，
为每个订阅生成 dialer-proxy 指向正确代理组的 Script。

使用 Script 而非 amendment 文件，因为 Script 在所有配置合并后执行，
可以正确引用订阅中已有的代理组（如 relay 的第一跳）。
"""

import argparse
import copy
import json
import random
import shutil
import string
import sys
import time
from pathlib import Path

import yaml


DEFAULT_PROFILES_DIR = Path.home() / "Library/Application Support/io.github.clash-verge-rev.clash-verge-rev/profiles"
PROJECT_ROOT = Path(__file__).resolve().parents[2]

DIALER_PROXY_PLACEHOLDER = "__DIALER_PROXY__"

EMPTY_SCRIPT = """\
// Define main function (script entry)

function main(config, profileName) {
  return config;
}
"""


def load_yaml(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def generate_uid(length: int = 12) -> str:
    """生成与 Clash Verge Rev 格式一致的随机 UID。"""
    chars = string.ascii_letters + string.digits
    return "".join(random.choices(chars, k=length))


def save_yaml(path: Path, data: dict) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Profiles Config for Clash Verge\n\n")
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)


def create_script_enhancement(profiles_yaml: Path, profiles_dir: Path, subscription_item: dict) -> str:
    """为订阅自动创建 Script 类型增强，返回新的 script UID。"""
    data = load_yaml(profiles_yaml)
    new_uid = generate_uid()
    now = int(time.time())

    new_item = {
        "uid": new_uid,
        "type": "script",
        "name": None,
        "file": f"{new_uid}.js",
        "updated": now,
    }
    data.setdefault("items", []).append(new_item)

    for item in data["items"]:
        if item.get("uid") == subscription_item.get("uid"):
            item.setdefault("option", {})["script"] = new_uid
            break

    save_yaml(profiles_yaml, data)

    script_path = profiles_dir / f"{new_uid}.js"
    script_path.write_text(EMPTY_SCRIPT, encoding="utf-8")

    print(f"  已自动创建 Script 增强: {new_uid}")
    return new_uid


def detect_main_group(profiles_dir: Path, subscription_uid: str) -> str | None:
    """读取订阅 YAML，返回第一个 proxy-group 的 name 作为主代理组。"""
    sub_path = profiles_dir / f"{subscription_uid}.yaml"
    if not sub_path.is_file():
        return None
    data = load_yaml(sub_path)
    groups = data.get("proxy-groups", [])
    if groups and isinstance(groups[0], dict):
        return groups[0].get("name")
    return None


def find_all_subscriptions(profiles_yaml: Path, profiles_dir: Path) -> list[dict]:
    """从 profiles.yaml 找到所有 remote 订阅及其 script UID。
    如果订阅未配置 script，自动创建一个。
    返回 [{uid, name, script_uid}, ...]。
    """
    data = load_yaml(profiles_yaml)
    results = []

    for item in data.get("items", []):
        if item.get("type") != "remote":
            continue

        uid = item["uid"]
        name = item.get("name", uid)
        option = item.get("option") or {}
        script_uid = option.get("script")

        if not script_uid:
            print(f"订阅 '{name}' 未配置 Script 增强，正在自动创建...")
            script_uid = create_script_enhancement(profiles_yaml, profiles_dir, item)

        results.append({"uid": uid, "name": name, "script_uid": script_uid})

    return results


def replace_dialer_proxy(proxies: list, dialer_proxy: str) -> list:
    """深拷贝 proxies 列表，将 dialer-proxy 占位符替换为实际值。"""
    result = copy.deepcopy(proxies)
    for proxy in result:
        if proxy.get("dialer-proxy") == DIALER_PROXY_PLACEHOLDER:
            proxy["dialer-proxy"] = dialer_proxy
    return result


def generate_script(proxies: list, groups: list, rules: list) -> str:
    """生成注入用的 JavaScript 脚本。"""
    lines = [
        "// Auto-generated by inject.py - 住宅IP链式代理注入",
        "// 请勿手动编辑此文件，修改 injection_component.yaml 后重新运行 inject.py",
        "",
        "function main(config, profileName) {",
    ]

    if proxies:
        lines.append("  // 注入代理节点")
        for proxy in proxies:
            lines.append(f"  config.proxies.push({json.dumps(proxy, ensure_ascii=False)});")
        lines.append("")

    if groups:
        lines.append("  // 注入代理组 (push 到末尾，确保引用的代理组已存在)")
        for group in groups:
            lines.append(f'  config["proxy-groups"].push({json.dumps(group, ensure_ascii=False)});')
        lines.append("")

    if rules:
        lines.append("  // 注入分流规则 (unshift 到最前面，优先级最高)")
        rules_json = json.dumps(rules, ensure_ascii=False)
        lines.append(f"  config.rules.unshift(...{rules_json});")
        lines.append("")

    lines.append("  return config;")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Clash Verge Rev 住宅IP链式代理注入工具 (多订阅)")
    parser.add_argument(
        "--profiles-dir",
        type=Path,
        default=DEFAULT_PROFILES_DIR,
        help=f"Clash Verge profiles 目录 (默认: {DEFAULT_PROFILES_DIR})",
    )
    parser.add_argument(
        "--component",
        type=Path,
        default=PROJECT_ROOT / "injection_component.yaml",
        help="注入配置文件路径 (默认: ./injection_component.yaml)",
    )
    parser.add_argument("--dry-run", action="store_true", help="预览模式，不写入文件")
    parser.add_argument("--clean", action="store_true", help="清除已注入的内容，恢复空脚本")
    args = parser.parse_args()

    profiles_dir = args.profiles_dir.expanduser()
    if not profiles_dir.is_dir():
        print(f"错误: profiles 目录不存在: {profiles_dir}", file=sys.stderr)
        sys.exit(1)

    profiles_yaml = profiles_dir.parent / "profiles.yaml"
    if not profiles_yaml.is_file():
        print(f"错误: profiles.yaml 不存在: {profiles_yaml}", file=sys.stderr)
        sys.exit(1)

    subscriptions = find_all_subscriptions(profiles_yaml, profiles_dir)
    if not subscriptions:
        print("错误: 未找到任何 remote 订阅", file=sys.stderr)
        sys.exit(1)

    print(f"找到 {len(subscriptions)} 个订阅:")
    for sub in subscriptions:
        main_group = detect_main_group(profiles_dir, sub["uid"])
        sub["main_group"] = main_group
        print(f"  - {sub['name']} ({sub['uid']}) → 主代理组: {main_group or '未知'}")

    # 清除模式
    if args.clean:
        print(f"\n{'='*50}")
        print(" 清除模式" + (" (预览)" if args.dry_run else ""))
        print(f"{'='*50}")

        for sub in subscriptions:
            script_path = profiles_dir / f"{sub['script_uid']}.js"
            print(f"\n  [{sub['name']}] {script_path.name}")
            if args.dry_run:
                print("    将恢复为空脚本")
            else:
                if script_path.is_file():
                    shutil.copy2(script_path, script_path.with_suffix(".js.bak"))
                script_path.write_text(EMPTY_SCRIPT, encoding="utf-8")
                print("    已恢复为空脚本")

        print("\n清除完成! 请在 Clash Verge Rev 中刷新配置使其生效。")
        return

    # 注入模式
    component_path = args.component
    if not component_path.is_file():
        print(f"错误: 注入配置文件不存在: {component_path}", file=sys.stderr)
        sys.exit(1)

    component = load_yaml(component_path)
    proxies_template = component.get("proxies", [])
    groups = component.get("proxy-groups", [])
    rules = component.get("rules", [])

    if not proxies_template and not groups and not rules:
        print("错误: injection_component.yaml 中没有任何内容可注入", file=sys.stderr)
        sys.exit(1)

    print(f"\n{'='*50}")
    print(" 注入模式" + (" (预览)" if args.dry_run else ""))
    print(f"{'='*50}")

    if proxies_template:
        print(f"  代理节点: {len(proxies_template)} 个")
    if groups:
        for g in groups:
            print(f"  代理组: {g['name']} (type: {g['type']})")
    if rules:
        print(f"  分流规则: {len(rules)} 条")

    for sub in subscriptions:
        main_group = sub["main_group"]
        script_path = profiles_dir / f"{sub['script_uid']}.js"

        print(f"\n  [{sub['name']}] dialer-proxy → \"{main_group}\"")

        if not main_group:
            print("    跳过: 无法检测主代理组")
            continue

        proxies = replace_dialer_proxy(proxies_template, main_group)
        script_content = generate_script(proxies, groups, rules)

        if args.dry_run:
            print(f"    [预览] 将写入 {script_path.name}:")
            print("    " + "-" * 40)
            for line in script_content.splitlines():
                print(f"    {line}")
        else:
            if script_path.is_file():
                shutil.copy2(script_path, script_path.with_suffix(".js.bak"))
            script_path.write_text(script_content, encoding="utf-8")
            print(f"    已写入: {script_path.name}")

    print("\n注入完成! 请在 Clash Verge Rev 中刷新配置使其生效。")


if __name__ == "__main__":
    main()
